### ISSUE TITLE
couldn't find cmp-server plugin with name argocd-lovely-plugin supporting the given repository

### ISSUE THREAD

**Issue by jannes-stubbemann-20230331** [crumbhole/argocd-lovely-plugin#177]
Hi there,

I have installed argocd with the plugin using the resources here: https://github.com/crumbhole/argocd-lovely-plugin/tree/main/examples/installation/argocd-sidecar.

I am having an applicationset with

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - git:
              repoURL: git@github.com:/organization/repo
              revision: HEAD
              files:
                - path: apps/**/overlays/{{ name }}/kustomization.yaml
template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: '{{ path[0] }}'
      name: '{{ name }}-{{ path[1] }}'
      namespace: argocd
    spec:
      destination:
        namespace: '{{ path[1] }}'
        server: '{{ server }}'
      source:
        path: apps/{{ path[1] }}/overlays/{{ name }}
        repoURL: git@github.com:/organization/repo
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
      project: default
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
```

in argocd ui, each application is giving the following error

> rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. couldn't find cmp-server plugin with name argocd-lovely-plugin supporting the given repository

I would expect the example to work out of the box. What am I missing?
