### ISSUE TITLE
characters dropped after $

### ISSUE THREAD

**Issue by Mitchell-Blanchard** [crumbhole/argocd-lovely-plugin#18]
when using kustomize_patch as per below, anything attached to $ disappears from the render, there doesnt appear to be an escape key either to stop this from happening.
```
plugin:
  name: argocd-lovely-plugin
  env:
    - name: LOVELY_KUSTOMIZE_PATCH
      value: |-
        - op: replace
          path: /patches/0/patch
          value: |-
            - op: add
              path: /data/agent3.yaml
              value: $value
```
So in the above example the entire "$value" will disappear and leave it empty.

My use case is patching in configs for an prometheus that includes scraping configs that require variables such as "$1:$2" which are dropped and rendered as ":"
