### ISSUE TITLE
LOVELY_HELM_VALUES don't respect values files in upper directory

### ISSUE THREAD

**Issue by jakuboskera** [crumbhole/argocd-lovely-plugin#182]
I got this error when I wanted to use `custom-values.yaml` file from upper directory `../values/`.

`ComparisonError
rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: argocd-lovely-plugin failed exit status 1: 2023/05/25 08:44:04 error running helm: exit status 1: Error: open ../values/custom-values.yaml: no such file or directory`

I have this repository stucture

```bash
.
├── test-argocd-plugin
│   ├── Chart.lock
│   ├── Chart.yaml
│   ├── charts
│   │   └── hello-world-0.1.0.tgz
│   ├── kustomization.yaml
│   ├── liveness-patch.yml
│   ├── templates
│   │   ├── configmap.yaml
│   │   └── secret.yaml
│   └── values.yaml
└── values
    └── custom-values.yaml
```

ArgoCD Application manifest for this app

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argocd-plugin
  namespace: argocd
spec:
  destination:
    url: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    plugin:
      name: argocd-lovely-plugin-v1.0
      env:
        - name: LOVELY_HELM_NAME
          value: foo
        - name: LOVELY_HELM_REPO_ADD_PARAMS
          value: --insecure-skip-tls-verify
        - name: LOVELY_HELM_VALUES
          value: "../values/custom-values.yaml"
    path: test-argocd-plugin
    repoURL: '<git repo>'
    targetRevision: master
```

Without plugin it works, but doesn't work with the `argocd-lovely-plugin`.

argocd-lovely-plugin: 0.18.0
ArgoCD version: v2.7.1+5e54351.dirty

**Comment by Joibel** [comment]
Please have a look at the `LOVELY_ALLOW_GITCHECKOUT` option and associated documentation/caveats and see if that helps.

**Comment by jakuboskera** [comment]
Seems to be working. According documentation it means that I have to set `lockRepo: true` for the plugin if more than one ArgoCD Application reference the same Git repository?

```diff
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argocd-plugin
  namespace: argocd
spec:
  destination:
    url: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    plugin:
      name: argocd-lovely-plugin-v1.0
      env:
        - name: LOVELY_HELM_NAME
          value: foo
        - name: LOVELY_HELM_REPO_ADD_PARAMS
          value: --insecure-skip-tls-verify
        - name: LOVELY_HELM_VALUES
          value: "../values/custom-values.yaml"
+       - name: LOVELY_ALLOW_GITCHECKOUT
+         value: "true"
    path: test-argocd-plugin
    repoURL: '<git repo>'
    targetRevision: master
```

**Comment by Joibel** [comment]
Yes, that is correct, you should set `lockRepo: true`

**Comment by jakuboskera** [comment]
Could you give me please example manifest of ConfigManagementPlugin with the `lockRepo: true` for the `argocd-lovely-plugin`? Or just hint where to set this option? Thanks

**Comment by Joibel** [comment]
Ah, if you're using lovely as a sidecar you don't need lockRepo, it's only needed for configmap plugins. Just carry on as you were.

**Comment by Joibel** [comment]
I need to sort out the documentation etc better for sidecars. Apologies for wasting your time.

**Comment by jakuboskera** [comment]
Yes basically I install argocd via original Helm Chart directly from argo-helm repo and I use these values

```yaml
repoServer:
  extraContainers:
    - name: lovely-plugin
      command: [/var/run/argocd/argocd-cmp-server]
      image: ghcr.io/crumbhole/argocd-lovely-plugin-cmp-vault:0.18.0
      envFrom:
        - secretRef:
            name: argocd-vault-replacer-credentials
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp-dir
  volumes:
    - name: tmp-dir
      emptyDir: {}
```
