### ISSUE TITLE
sidecar plugins of lovely plugin

### ISSUE THREAD

**Issue by dels78** [crumbhole/argocd-lovely-plugin#193]
Hello!

I have been struggling with finding the proper way to define a _non-lovely_ (argocd-vault-plugin) plugin as a plugin of lovely-plugin.

I dug into the multiple installation examples, including the deprecated ones, but no matter what I am not able to use the argocd-vault-plugin in combination with lovely.

the error I am seeing:
```
rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `argocd-lovely-plugin` failed exit status 1: 2023/06/08 20:53:40 exit status 127: bash: line 1: argocd-vault-plugin-kustomize: command not found
``` 

I am unsure how lovely is trying to run its plugins nor how the sidecars share anything other than the cmp-plugin volumeMount, which only has the `.sock` file for each of the sidecars.

Unfortunately I cannot use your vault replacement as it doesn't seem to support 1Password connect so I was hoping to combine the other plugins with lovely.

here is the relevant part of my values file for argocd repo server:
```yml
 # -- load env from secret
    envFrom:
      - secretRef:
          name: argocd-vault-plugin-credentials
    # -- init container to download vault plugin
    initContainers:
      - name: download-tools
        image: registry.access.redhat.com/ubi8
        env:
          - name: AVP_VERSION
            # renovate: datasource=github-releases depName=argoproj-labs/argocd-vault-plugin
            value: 1.14.0
        command: [sh, -c]
        args:
          - >-
            curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
    # -- sidecars to run vault plugin
    extraContainers:
      # -- argocd-vault-plugin with Helm
      - name: avp-helm
        command: [/var/run/argocd/argocd-cmp-server]
        image: quay.io/argoproj/argocd:v2.7.4
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        envFrom:
          - secretRef:
              name: argocd-vault-plugin-credentials
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp
          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-helm.yaml
            name: cmp-plugin

          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin

      # argocd-vault-plugin with Kustomize
      - name: avp-kustomize
        command: [/var/run/argocd/argocd-cmp-server]
        image: quay.io/argoproj/argocd:v2.7.4
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        envFrom:
          - secretRef:
              name: argocd-vault-plugin-credentials
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp

          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-kustomize.yaml
            name: cmp-plugin

          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin

      # argocd-vault-plugin with plain YAML
      - name: avp
        command: [/var/run/argocd/argocd-cmp-server]
        image: quay.io/argoproj/argocd:v2.7.4
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        envFrom:
          - secretRef:
              name: argocd-vault-plugin-credentials
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp

          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp.yaml
            name: cmp-plugin

          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin

      # -- sidecar to run lovely plugin
      - name: lovely-plugin
        # This command is actually already set in the image.
        command: [/var/run/argocd/argocd-cmp-server]  # Entrypoint should be Argo CD lightweight CMP server i.e. argocd-cmp-server
        # Choose your image here - this one has vault replacer in it
        image: ghcr.io/crumbhole/argocd-lovely-plugin-cmp:0.19.1
        env:
          - name: LOVELY_PLUGINS
            value: argocd-vault-plugin-kustomize, argocd-vault-plugin-helm, argocd-vault-plugin
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          # Import the repo-server's plugin binary
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
            # Starting with v2.4, do NOT mount the same tmp volume as the repo-server container. The filesystem separation helps
            # mitigate path traversal attacks.
          - mountPath: /tmp
            name: lovely-tmp
    volumes:
      # A temporary directory for the lovely plugin to work in.
      - emptyDir: {}
        name: lovely-tmp
      # Volumes for cmp-plugins
      - configMap:
          name: cmp-plugin
        name: cmp-plugin
      - name: custom-tools
        emptyDir: {}
      - name: tmp
        emptyDir: {}
```

Here is the configmap of the different avp sidecars
```yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true

      # Note: this command is run _before_ anything is done, therefore the logic is to check
      # if this looks like a Kustomize bundle
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yaml
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate -"
      lockRepo: false
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true

      # Note: this command is run _before_ any Helm templating is done, therefore the logic is to check
      # if this looks like a Helm chart
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
      generate:
        # **IMPORTANT**: passing `${ARGOCD_ENV_helm_args}` effectively allows users to run arbitrary code in the Argo CD
        # repo-server (or, if using a sidecar, in the plugin sidecar). Only use this when the users are completely trusted. If
        # possible, determine which Helm arguments are needed by your users and explicitly pass only those arguments.
        command:
          - sh
          - "-c"
          - |
            helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . |
            argocd-vault-plugin generate --verbose-sensitive-output -
      lockRepo: false
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - "generate"
          - "."
      lockRepo: false
---
```

**Comment by Joibel** [comment]
Lovely cannot access other sidecar plugins. I'm sorry this isn't clear in the docs.

Helm and kustomize are built in, so no need to have them at all, lovely should "Do the right thing"(tm) for applications with those (as long as you're using `Chart.yaml`s for helm charts).

To use argocd-vault-plugin download it into the lovely sidecar somewhere on the path (/usr/local/bin I'd sugges), and then set the ARGOCD_LOVELY_PLUGINS to just `argocd-vault-plugin generate -`

If argocd-vault-plugin doesn't play well with processing all the yaml thrown at it (as in it must replace something or it gets upset) then you may need an alternative approach.

I'd be curious as to where you get to with this. I initially started with that plugin, but quickly wrote the alternative when it didn't work for me. They've moved on a lot since then - if it's a viable plugin I'll publish a version of lovely with it working.

**Comment by dels78** [comment]
hah, that makes sense then!

I like your thought process on how to make it happen, I thought about doing it but I thought that maybe the plugin system had a way to share the execution between sidecars.

I appreciate the quick response, I'll be playing around with this and report back!

**Comment by dels78** [comment]
reporting back... it works!

Here's how I ended up configuring it, super easy.

```yml
  ## Plugins
  repoServer:
    serviceAccount:
      automountServiceAccountToken: true
    # -- rbac config for vault plugin
    rbac:
      - verbs:
          - get
          - list
          - watch
        apiGroups:
          - ''
        resources:
          - secrets
          - configmaps
    # -- load env from secret
    envFrom:
      - secretRef:
          name: argocd-vault-plugin-credentials
    # -- init container to download vault plugin
    initContainers:
      - name: download-tools
        image: registry.access.redhat.com/ubi8
        env:
          - name: AVP_VERSION
            # renovate: datasource=github-releases depName=argoproj-labs/argocd-vault-plugin
            value: 1.14.0
        command: [sh, -c]
        args:
          - >-
            curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
    # -- sidecars to run vault plugin
    extraContainers:
      # -- sidecar to run lovely plugin
      - name: lovely-plugin
        # This command is actually already set in the image.
        command: [/var/run/argocd/argocd-cmp-server]  # Entrypoint should be Argo CD lightweight CMP server i.e. argocd-cmp-server
        # Choose your image here - this one has vault replacer in it
        image: ghcr.io/crumbhole/argocd-lovely-plugin-cmp:0.19.1
        env:
          - name: LOVELY_PLUGINS
            value: argocd-vault-plugin generate -
        envFrom:
          - secretRef:
              name: argocd-vault-plugin-credentials
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          # Import the repo-server's plugin binary
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
            # Starting with v2.4, do NOT mount the same tmp volume as the repo-server container. The filesystem separation helps
            # mitigate path traversal attacks.
          - mountPath: /tmp
            name: lovely-tmp
          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin

    volumes:
      # A temporary directory for the lovely plugin to work in.
      - emptyDir: {}
        name: lovely-tmp
      # Volumes for cmp-plugins
      - name: custom-tools
        emptyDir: {}
      - name: tmp
        emptyDir: {}
```
