### ISSUE TITLE
Question: How to use argocd-vault-plugin for multiple Vault instances

### ISSUE THREAD

**Issue by jakuboskera** [crumbhole/argocd-lovely-plugin#231]
Is there any way to use argocd-lovely-plugin with multiple instances of argocd-vault-plugin, meaning that we can use multiple instances of vault and each argocd-vault-plugin will be configured to work with the specific vault? The current setup expected just one instance of the vault.

Thanks

**Comment by Joibel** [comment]
Humm, to do this you need two differently named (or differently versioned which would be weird) copies of lovely-vault-plugin.

You could do this by building a derived version of the docker image with `/home/argocd/cmp-server/config/plugin.yaml` having a different name. Or a shell script to patch this in at startup.

It seems useful to be able to drive the name of lovely via an environment variable, so you could do this without needing to do any more work than just add one more config to the plugin. I'll look into that.

**Comment by jakuboskera** [comment]
I see that you have implemented this feature. Could you give me please some example how to use it? Let's say I have two vaults which use different VAULT_ADDR environment variable...

Many thanks

**Comment by Joibel** [comment]
Install the plugin twice, with different names:
```
spec:
  template:
    spec:
      containers:
        - name: lovely-plugin-foo
          image: ghcr.io/crumbhole/lovely-vault-plugin:0.20.1
          env:
          - name: VAULT_ADDR
            value: http://vault.foo
          - name: PLUGIN_NAME
            value: lovely-vault-plugin-foo
```
and again with
```
spec:
  template:
    spec:
      containers:
        - name: lovely-plugin-bar
          image: ghcr.io/crumbhole/lovely-vault-plugin:0.20.1
          env:
          - name: VAULT_ADDR
            value: http://vault.bar.com
          - name: PLUGIN_NAME
            value: lovely-vault-plugin-bar
```
You probably actually want to get the `envFrom` secrets, but I hope this gives you the idea.

Use the plugin by the value from `PLUGIN_NAME`, so you'd set in the application
```
spec:
  source:
     plugin:
        name: lovely-vault-plugin-foo
```
In this case we're overriding both plugin names with different ones, but you could only set one PLUGIN_NAME, and then the other would be called the default `lovely-vault-plugin`
