### ISSUE TITLE
ci: CI always fails for users who offer PRs

### ISSUE THREAD

**Issue by tico24** [crumbhole/argocd-lovely-plugin#269]
It seems that the ci ghcr creds aren't available to users who offer PRs to this project. They are only available to cool people like myself and @Joibel.

Other github projects don't have this issue, so we've done some incorrect setup that I don't yet understand.

**Comment by clementnuss** [comment]
just as a side note, it's probably not a good idea to automatically grant access to `GITHUB_TOKEN` to ~cool~ external people (like me): it's then quite simple to create a PR to extract the token and do nasty thing 😈 

some more info can be found [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository)

**Comment by Joibel** [comment]
Indeed. We don't auto run PRs from non-cool people, but it's not really good practice.

**Comment by clementnuss** [comment]
you can refer to one of my project to solve this: https://github.com/postfinance/kubelet-csr-approver/blob/main/.github/workflows/publish.yaml#L8

basically I added a `check-dockerhub-token` job:
```yaml
jobs:
  check-dockerhub-token:
    runs-on: ubuntu-latest
    outputs:
      HAS_DOCKERHUB_TOKEN: ${{ steps.gh-token.outputs.HAS_DOCKERHUB_TOKEN }}
    steps:
      - id: gh-token
        env:
          HAS_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN != '' }}
        run: |
          echo "HAS_DOCKERHUB_TOKEN=$HAS_DOCKERHUB_TOKEN" >> $GITHUB_OUTPUT
          echo "HAS_DOCKERHUB_TOKEN=$HAS_DOCKERHUB_TOKEN" >> $GITHUB_STEP_SUMMARY
```

and then in later jobs, I add an `if` statement such as:

```yaml
  publish-tagged:
    needs:
      - lint
      - test
      - check-dockerhub-token
    if: |
      startsWith(github.ref, 'refs/tags/v') &&
      !github.event.pull_request.head.repo.fork &&
      needs.check-dockerhub-token.outputs.HAS_DOCKERHUB_TOKEN == 'true'
```
