### ISSUE TITLE
401 unauthorized - Unable to pull OCI Registry images on Lovely CMP 0.22.1 (Helm 1.13.1)

### ISSUE THREAD

**Issue by KevinBonilla** [crumbhole/argocd-lovely-plugin#347]
Hello, in my teams environment I pull Azure ACR helm charts via OCI. Currently we are experiencing issues with lovely causing this error: 
```
"Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `argocd-lovely-plugin` failed exit status 1: 2023/12/05 14:58:18 exit status 1: Error: could not download oci://$ACR_NAME.azurecr.io/helm/<helm chart>: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://<$HELM_ACR_URL>.azurecr.io: 401 Unauthorized" 
```

Scenario:
1. Create an ApplicationSet, invoke the lovely plugin. Since it is installed on all argocd-repo-servers this causes issues with our ApplicationSets.
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-appset-staging
  namespace: argocd
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator, 'child' #1
          - git:
              directories:
                - path: "*"
              repoURL: https://github.com/<git-org>/<git-repo>.git
              revision: HEAD
          # cluster generator, 'child' #2
          - clusters:
              selector:
                matchLabels:
                  environment: <cluster-label>
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: "<argo-project>"
      source:
        repoURL: https://github.corp.com/<git-org>/<git-repo>.git
        targetRevision: HEAD
        path: '{{path}}/{{metadata.labels.environment}}'
        plugin:
          name: argocd-lovely-plugin
      destination:
        server: '{{server}}'
        namespace: '<namespace>'
      syncPolicy:
        automated:
          selfHeal: true
 ```

2. Setup Chart.yaml 
```
apiVersion: v2
name: <helm-chart>
version: "0.1.0"
appVersion: 1.0.0
description: A Helm chart for <helm-chart>

dependencies:
- name: <helm-chart>
  version: 0.1.0
  namespace: <namespace>
  repository: oci://$ACR_URL/helm
````
I believe this issue roots from a Helm plugin update that happened here: https://github.com/crumbhole/argocd-lovely-plugin/pull/305

Resolution:
Upgrade from `Helm 1.13.1` to `Helm 1.13.2` and we should see this bug disappear

References: 
https://github.com/helm/helm/issues/12423
https://github.com/argoproj/argo-cd/issues/16320

Version:
```
ArgoCD:
    "Version": "v2.9.2+c5ea5c4",
    "HelmVersion": "v3.13.2+g2a2fb3b",
argocd-lovely-plugin-cmp:
    "Version": "0.22.1",
    "HelmVersion": "v3.13.1"
```

**Comment by KevinBonilla** [comment]
Application deploys when manifest is deployed **without** lovely: 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  destination:
    namespace: <namespace>
    server: 'https://kubernetes.default.svc'
  project: <project>
  source:
    helm:
      valueFiles:
      - values.yaml
    path: <path/to/helm-chart>
    repoURL: https://github.corp.com/<git-org>/<git-repo>.git
    targetRevision: HEAD
```

Application causing `401 unauthorized` when invoking lovely plugin:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  destination:
    namespace: <namespace>
    server: 'https://kubernetes.default.svc'
  project: <project>
  source:
    helm:
      valueFiles:
      - values.yaml
    path: <path/to/helm-chart>
    repoURL: https://github.corp.com/<git-org>/<git-repo>.git
    targetRevision: HEAD
    plugin:
       name: argocd-lovely-plugin
```
