### ISSUE TITLE
ARGOCD_ENV_LOVELY_HELM_PATCH  doesn't seem to work

### ISSUE THREAD

**Issue by tico24** [crumbhole/argocd-lovely-plugin#38]
I have the following applicationset for promtail:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: promtail-set
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            mycompany.biz/appset-common: "true"
  template:
    metadata:
      name: 'promtail-{{name}}'
    spec:
      destination:
        name: '{{name}}'
        namespace: promtail
      project: applicationsets
      source:
        path: pathy/path
        repoURL: 'gittygittgit.git'
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
          env:                                                                                                                                                                                         
            - name: ARGOCD_ENV_LOVELY_HELM_PATCH                                                                                                                                                                  
              value: |                                                                                                                                                                                 
                [{ "op": "add", "path": "/promtail/config/snippets/common/7", "value": { "action": "replace", "replacement": "{{name}}", "target_label": "cluster" } }]
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
```

However, when I exec into a promtail pod and perform `cat /etc/promtail/promtail.yaml` I don't see the expected:
```
      - action: replace
        replacement: my-cluster-name
        target_label: cluster
```

If I change `ARGOCD_ENV_LOVELY_HELM_PATCH` back to `LOVELY_HELM_PATCH`, I see my expected addition in the promtail.yaml file.

ArgoCD 2.4.6. Lovely 0.4.1

(Promtail Chart 6.2.1 for what it's worth)
