### ISSUE TITLE
Cant add helm repo if using helmfile processor

### ISSUE THREAD

**Issue by Yeradon** [crumbhole/argocd-lovely-plugin#397]
Im trying to use a simple helmfile to deploy helm charts to my cluster. The execution fails as soon as helmfile runs `helm repo add`, with the following error message:

`Error: mkdir /.config: permission denied`

Helm seems to use $HOME/.config as default data dir, since this env var isn't set it uses /.config, which isn't writable by the user used in the container (uid 999). 

<details>
  <summary>My helmfile</summary>

```yaml
repositories:
  - name: vault
    url: https://helm.releases.hashicorp.com
releases:
  - name: vault
    namespace: vault
    chart: vault/vault 
    version: 0.27.0 

 ```
</details>

<details>
  <summary>My argocd app:</summary>

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-cloud
  namespace: argocd
 
spec:
  destination:
    name: cloud
    namespace: vault
  project: default
  source:
    path: vault
    plugin:
      env:
        - name: LOVELY_HELMFILE_TEMPLATE_PARAMS
          value: >-
            --values values.yaml helmfile-values-cloud.yaml
      name: argocd-lovely-plugin
    repoURL: ***
  syncPolicy:
    automated:
    selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
</details>

<details>
  <summary>Full error log with helmfile debug mode</summary>

```
time="2024-01-26T13:35:41Z" level=error msg="`argocd-lovely-plugin` failed exit status 1: 2024/01/26 13:35:41 error running helmfile: exit status 1: processing file \"helmfile.yaml\" in directory \".\"
changing working directory to \"/tmp/_cmp_server/a0a0eeaa-984a-4f44-85f7-8c5784b6cc88/vault\"
first-pass rendering starting for \"helmfile.yaml.part.0\": inherited=&{default  map[] map[]}, overrode=<nil>
first-pass uses: &{default  map[] map[]}
first-pass rendering output of \"helmfile.yaml.part.0\":
 0: repositories:
 1:   - name: vault
 2:     url: https://helm.releases.hashicorp.com
 3: helmDefaults:
 4:   args:
 5:     - \"--registry-config /tmp/.helm/registry.json\" 
 6:     - \"--repository-cache /tmp/.helm/cache/repository\"
 7:     - \"--repository-config /tmp/.helm/repositories.json\"
 8: releases:
 9:   - name: vault
10:     namespace: vault
11:     chart: vault/vault 
12:     version: 0.27.0 
13: 
14:     

first-pass produced: &{default  map[] map[]}
first-pass rendering result of \"helmfile.yaml.part.0\": {default  map[] map[]}
vals:
map[]
defaultVals:[]
second-pass rendering result of \"helmfile.yaml.part.0\":
 0: repositories:
 1:   - name: vault
 2:     url: https://helm.releases.hashicorp.com
 3: helmDefaults:
 4:   args:
 5:     - \"--registry-config /tmp/.helm/registry.json\" 
 6:     - \"--repository-cache /tmp/.helm/cache/repository\"
 7:     - \"--repository-config /tmp/.helm/repositories.json\"
 8: releases:
 9:   - name: vault
10:     namespace: vault
11:     chart: vault/vault 
12:     version: 0.27.0 
13: 
14:     

merged environment: &{default  map[] map[]}
helm:Rmjwt> v3.13.3+gc8b9489
helm:Rmjwt> 
Adding repo vault https://helm.releases.hashicorp.com
exec: helm repo add vault https://helm.releases.hashicorp.com --force-update
helm:deTUR> Error: mkdir /.config: permission denied
helm:deTUR> 
err: command \"/usr/local/bin/helm\" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: repo (4 bytes)
  2: add (3 bytes)
  3: vault (5 bytes)
  4: https://helm.releases.hashicorp.com (35 bytes)
  5: --force-update (14 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: mkdir /.config: permission denied

COMBINED OUTPUT:
  Error: mkdir /.config: permission denied
changing working directory back to \"/tmp/_cmp_server/a0a0eeaa-984a-4f44-85f7-8c5784b6cc88/vault\"
in ./helmfile.yaml: command \"/usr/local/bin/helm\" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: repo (4 bytes)
  2: add (3 bytes)
  3: vault (5 bytes)
  4: https://helm.releases.hashicorp.com (35 bytes)
  5: --force-update (14 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: mkdir /.config: permission denied

COMBINED OUTPUT:
  Error: mkdir /.config: permission denied" execID=c032d

```

</details>

I can see that, the helm processor sets the following baseParams: ``--registry-config`, `/tmp/.helm/registry.json`, `--repository-cache`, `/tmp/.helm/cache/repository`, `--repository-config`, `/tmp/.helm/repositories.json``. I am unsure if these fix the problems, as i have found no way to pass them to helm, when using helmfiles.

I tried to add those params in the helmfile, and as command arguments:

```yaml
helmDefaults:
  args:
    - "--registry-config /tmp/.helm/registry.json" 
    - "--repository-cache /tmp/.helm/cache/repository"
    - "--repository-config /tmp/.helm/repositories.json"
```
```yaml
- name: LOVELY_HELMFILE_TEMPLATE_PARAMS
          value: >-
            --args '--registry-config /tmp/.helm/registry.json
            --repository-cache /tmp/.helm/cache/repository --repository-config
            /tmp/.helm/repositories.json' --log-level debug --values values.yaml
            helmfile-values-cloud.yaml}
```
Unfortunately none of this configurations seems to influence the `helm repo add` command, as it failed the same way every time.

I also tried to set environment vars for helm to use a different directory:

```yaml
        plugin:
          name: argocd-lovely-plugin
          env:
          - name: HELM_CACHE_HOME
            value: /tmp/helm
          - name: HELM_DATA_HOME
            value: /tmp/helm
          - name: HELM_CONFIG_HOME
            value: /tmp/helm
```

 It seems that those env vars, dont get passed to the helm process. I am unsure if thats because of this plugin or helmfile, but i suspect this plugin to not pass those env vars. Is that assumption correct? If so, is there a way to pass env vars to the execution environment?
