### ISSUE TITLE
Issue with helmfile and capabilities

### ISSUE THREAD

**Issue by davidfrickert** [crumbhole/argocd-lovely-plugin#504]
Having an issue with helmfile and a chart that uses `.Capabilities.APIVersions.has`. Any idea on how to overcome?
I actually have the required CRDs but it seems that helm template command does not check the cluster.

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `argocd-lovely-plugin` failed exit status 1: 2024/06/06 18:12:56 error running helmfile: exit status 1: Adding repo traefik https://traefik.github.io/charts "traefik" has been added to your repositories Templating release=traefik, chart=traefik/traefik in ./helmfile.yaml: command "/usr/local/bin/helm" exited with non-zero status: PATH: /usr/local/bin/helm ARGS: 0: helm (4 bytes) 1: template (8 bytes) 2: traefik (7 bytes) 3: traefik/traefik (15 bytes) 4: --version (9 bytes) 5: 28.2.0 (6 bytes) 6: --namespace (11 bytes) 7: kube-system (11 bytes) 8: --values (8 bytes) 9: /tmp/helmfile2658468773/kube-system-traefik-values-7b8c868556 (61 bytes) 10: --include-crds (14 bytes) ERROR: exit status 1 EXIT STATUS 1 STDERR: Error: execution error at (traefik/templates/servicemonitor.yaml:5:10): ERROR: You have to deploy monitoring.coreos.com/v1 first Use --debug flag to render out invalid YAML COMBINED OUTPUT: Error: execution error at (traefik/templates/servicemonitor.yaml:5:10): ERROR: You have to deploy monitoring.coreos.com/v1 first Use --debug flag to render out invalid YAML
```

**Comment by davidfrickert** [comment]
Okay, adding this to helmfile.yaml seems to work:

```
apiVersions:
  - "monitoring.coreos.com/v1"
```

I wonder though, on a regular argocd helm installation this is not needed. is there any possible improvement here to make it work without needing to manually specify apiVersions?

**Comment by davidfrickert** [comment]
It seems that argo populates the helm template apiversions, that's why it is not an issue.
https://github.com/argoproj/argo-cd/pull/7519

Could lovely plugin mirror this behaviour?

**Comment by Joibel** [comment]
At the moment ArgoCD doesn't send this information to plugins, so it's not possible to implement in a plugin. You can get around it in various ways, including the one kind of documented here https://github.com/crumbhole/argocd-lovely-plugin/tree/main/test/helm_k8_rbac_api_version_v2

**Comment by fernandezcuesta** [comment]
That's weird because I see the apiversions for the destination cluster available in `$KUBE_API_VERSIONS`, which any plugin can read.

**Comment by ashtonian** [comment]
Having issues as well. The helm processor looks to be [mapping the env](https://github.com/crumbhole/argocd-lovely-plugin/blob/main/pkg/processor/helmProcessor.go#L147-L155) fields. The kustomize plugin is not setting `--helm-kube-version` or `--helm-api-versions`, so if you are using kustomize to expand the charts it won't work properly.

**Comment by ashtonian** [comment]
Fixed the kustomize issue temporarily with:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-lovely-plugin-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-lovely-plugin
    spec:
      version: v1.0
      allowConcurrency: true
      lockRepo: false
      generate:
        command:
          - sh
          - -c
          - |
            export LOVELY_KUSTOMIZE_PARAMS="--helm-kube-version=${KUBE_VERSION} --helm-api-versions=${KUBE_API_VERSIONS}"
            exec argocd-lovely-plugin
```

If you guys aren't using kustomize, could probably test something similar by  using 
```yaml
    generate:
        command:
          - sh
          - -c
          - |
          # TODO: split contents of ${KUBE_API_VERSIONS} on comma and append multiple  --helm-api-versions flags as helm doesn't handle comma separated list and expects multiple flags ie  --helm-api-versions=someapi  --helm-api-versions=someotherapi
            export LOVELY_HELM_TEMPLATE_PARAMS="--helm-kube-version=${KUBE_VERSION} --helm-api-versions=${KUBE_API_VERSIONS}"
            exec argocd-lovely-plugin
```

This is also encouraging in that the code for helm processor as is should be handling it.
