### ISSUE TITLE
Install with ArgoCD Operator

### ISSUE THREAD

**Issue by diskmanti** [crumbhole/argocd-lovely-plugin#549]
Hello everyone,

I am trying to install lovely on an ArgoCD managed with the ArgoCD operator. I could not find specific instructions on the repo for operator installation.

Following the [ArgoCD Operator docs ](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#register-the-plugin-sidecar) and the lovely docs I came up with this ArgoCD CR manifest:
```yaml
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: cluster
  namespace: argocd-system
spec:  
  applicationSet:
    enabled: true
  repo:
    sidecarContainers:
      - name: lovely-plugin
        command: [/var/run/argocd/argocd-cmp-server]
        image: ghcr.io/crumbhole/argocd-lovely-plugin-cmp:1.0.3
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
            # Import the repo-server's plugin binary
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
            # Starting with v2.4, do NOT mount the same tmp volume as the repo-server container. The filesystem separation helps
            # mitigate path traversal attacks.
          - mountPath: /tmp
            name: lovely-tmp  
```

Using this manifest ArgoCD resources are not created. Can you please provided some info how to enable the plugin with ArgoCD operator.

Thank you
