### ISSUE TITLE
Weirdness in preprocessors

### ISSUE THREAD

**Issue by paveq** [crumbhole/argocd-lovely-plugin#58]
I'm using sed command in ARGOCD_ENV_LOVELY_PREPROCESSORS, as in one of the examples to replace contents of values.yaml.

Seems if sed returns error code due to eg. file not existing, lovely-plugin does not catch it, and happily just continues processing.

Instead, we should return error to argocd.

EDIT: seems my ENV variable name was wrong, LOVELY_PREPROCESSORS does work, however I still can't make it to find proper file. Following Application definition works, and replaces correctly:

```
  source:
    path: deploy/magento
    plugin:
      env:
      - name: LOVELY_PREPROCESSORS
        value: sed -i 's/<<environment>>/dev-lovely/g' values.yaml
      name: argocd-lovely-plugin
```

But if I try to target a directory above it, in order to include plain yaml files in another directory, I this fails:
```
  source:
    path: deploy
    plugin:
      env:
      - name: LOVELY_PREPROCESSORS
        value: sed -i 's/<<environment>>/dev-lovely/g' magento/values.yaml
      name: argocd-lovely-plugin
```

**Comment by paveq** [comment]
I got it working with:
```
  source:
    path: deploy
    plugin:
      env:
      - name: LOVELY_PREPROCESSORS
        value: sed -i 's/<<environment>>/dev-lovely/g' values.yaml || true
```
Seems preprocessors run per directory in deploy folder. I suppose this is intentional, however it might be good to mention in documentation.

**Comment by Joibel** [comment]
I have added the ability to configure preprocessors and plugins on a per sub-application basis. For your example try this:

```
  source:
    path: deploy
    plugin:
      env:
      - name: LOVELY_PREPROCESSORS_YAML
        value: |-
          magento:
          - "sed -i 's/<<environment>>/dev-lovely/g' values.yaml"
      name: argocd-lovely-plugin
```
