### ISSUE TITLE
Can we use multiple sources for an application with lovely?

### ISSUE THREAD

**Issue by AndrewSav** [crumbhole/argocd-lovely-plugin#618]
From <https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/>:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/charts/prometheus/values.yaml
  - repoURL: 'https://git.example.com/org/value-files.git'
    targetRevision: dev
    ref: values
```

This allows the helm tool to reference files from a different repo. How to achieve the same with lovely?
