### ISSUE TITLE
Integrating argocd-vault-plugin with argocd-lovely-plugin: Container Creation Error

### ISSUE THREAD

**Issue by Nivedita-coder** [crumbhole/argocd-lovely-plugin#619]
Hey folks,

I'm setting up the `argocd-vault-plugin` with the `argocd-lovely-plugin` to handle both `avp.helm` and `avp.kustomize` configurations in a single setup, so I can avoid running separate containers for each. Note: I'm installing argocd via helm installation

However, I'm running into an error when creating the container for the lovely plugin. Here’s my configuration for reference:

cmp.yaml:

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argocd
  name: cmp-plugin
data:
  avp-lovely.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      namespace: argocd
      name: avp-lovely
    spec:
      allowConcurrency: true
      discover:
        find:
          command: ["sh", "-c", "test -f kustomization.yaml && echo 'kustomize' || echo 'helm'"]
      generate:
        command:
          - sh
          - "-c"
          - |
            if [ -f "kustomization.yaml" ]; then
              kustomize build . | argocd-vault-plugin generate -
            elif [ -f "Chart.yaml" ]; then
              helm template $ARGOCD_APP_NAME --include-crds -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_HELM_ARGS} . | argocd-vault-plugin generate -
            else
              echo "No compatible manifests found."
      lockRepo: false
```

values.yaml:

```
repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
    - name: var-files
      emptyDir: {}
  volumeMounts:
    - name: custom-tools
      mountPath: /usr/local/bin/argocd-vault-plugin
    - name: cmp-plugin
      mountPath: /home/argocd/cmp-server/config/plugin.yaml
      subPath: avp-lovely.yaml
  envFrom:
    - secretRef:
        name: argocd-vault-plugin-credentials
  initContainers:
    - name: download-tools
      image: registry.access.redhat.com/ubi8
      command: [sh, -c]
      env:
        - name: AVP_VERSION
          value: 1.18.0
      args:
        - >
          curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 -o argocd-vault-plugin &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  extraContainers:
    - name: avp-lovely
      image: ghcr.io/crumbhole/lovely:1.1.1
      imagePullPolicy: Always
      command: [/var/run/argocd/argocd-cmp-server]
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 999
      envFrom:
        - secretRef:
            name: argocd-vault-plugin-credentials
      volumeMounts:
        - mountPath: /home/argocd/cmp-server/plugin.yaml #avp-lovely.yaml
          name: cmp-plugin
          subPath: avp-lovely.yaml
        - mountPath: /usr/local/bin/argocd-vault-plugin #argocd-vault-plugin
          name: custom-tools
          subPath: argocd-vault-plugin
        - mountPath: /var/run/argocd
          name: var-files

```
