### ISSUE TITLE
Lovely with helm-argocd-vault-replacer

### ISSUE THREAD

**Issue by paveq** [crumbhole/argocd-lovely-plugin#62]
I've configured lovely plugin with vault-replacer, and trying to use helm-argocd-vault-replacer as plugin for lovely. My use case is that we have in-house maintained Helm chart, that in one of it's secret retrieves Vault secret like this:

```
stringData:
  sftp.json: "<secret:sftp/data/login/{{ .Values.sftp.environment }}/users~{{ .Values.sftp.userName }}>"
```

As values are used in the secret template, I need to first render the Helm chart before filling in the secret templates.

My Application spec looks like:
```
    spec:
      source:
        path: 'deploy'
        plugin:
          name: argocd-lovely-plugin
          env:
            - name: LOVELY_PLUGINS
              value: helm-argocd-vault-replacer
            - name: LOVELY_PREPROCESSORS
              value: sed -i 's/<<environment>>/{{environment}}/g' values.yaml || true
```

Error I get is:
```
`argocd-lovely-plugin` failed exit status 1: 2022/09/27 05:19:57 exit status 127: bash: line 1: helm-argocd-vault-replacer: command not found`
```

Looking at source code in lovely plugin, all it tries is to execute plugins as commands. Are plugins in argo-cd configmap relevant at all as plugins for lovely, and can above scenario work at all?
