### ISSUE TITLE
Lovely throws an error when kustomize includes a base or directory up in tree

### ISSUE THREAD

**Issue by Tyrion85** [crumbhole/argocd-lovely-plugin#66]
Given a simple kustomization like
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/namespaces
```

and ArgoCD Application **without lovely plugin**, it works as expected, base is included and deployed properly.

However, when lovely plugin is included in the same Application:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
...
spec:
  source:
    ...
    path: k8s/[omitted]/overlays/_cluster/namespaces
    plugin:
      name: argocd-lovely-plugin
...
```

an error is thrown:
```
rpc error: code = Unknown desc = Manifest generation error (cached):
 `argocd-lovely-plugin` failed exit status 1: 2022/10/13 15:19:41 
Error: accumulating resources: accumulation 
err='accumulating resources from '../../../../base/namespaces': 
evalsymlink failure on '/base/namespaces' : 
lstat /base: no such file or directory': 
evalsymlink failure on '/base/namespaces' : 
lstat /base: no such file or directory
```

Does lovely plugin support inclusion of base?

ArgoCD version: 2.4.12
Lovely version: 0.6.4
Kustomize version: 4.4.1
