### ISSUE TITLE
Installation Documentation Contribution

### ISSUE THREAD

**Issue by excalq** [crumbhole/argocd-lovely-plugin#670]
Hello, and thank you for this _lovely_ plugin. 

I've recently completed installation of `argocd-lovely-plugin`, and would like to contribute some improvements to the installation documentation, in hopes of saving those ahead some time and frustration.

In my scenario, ArgoCD itself is installed via Helm, which I suspect is not uncommon. Via the [examples](https://github.com/crumbhole/argocd-lovely-plugin/tree/main/examples/installation/argocd-sidecar), I was able to translate this to `values.yaml` contents as follows:

> ArgoCD Installation Helm Chart:
```
repoServer:
  extraContainers:
    # ArgoCD Lovely Config Manager Plugin for better Helm+Kustomize support (https://github.com/crumbhole/argocd-lovely-plugin/)
    - name: lovely-plugin
      image: ghcr.io/crumbhole/lovely:1.2.0
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
          # Import the repo-server's plugin binary
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
          # Starting with v2.4, do NOT mount the same tmp volume as the repo-server container. The filesystem separation helps mitigate path traversal attacks.
        - mountPath: /tmp
          name: lovely-tmp
  volumes:
    - emptyDir: {}
      name: lovely-tmp
```

I'm not entirely sure why, but I was unable to get the plugin name `name: argocd-lovely-plugin-v1.0` to work, but poking around in the container's `/home/argocd/cmp-server/config/plugin.yaml` file showed the plug in to be called simply `lovely`, with no version set.

> ApplicationSet Configuration:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
...
    spec:
      ...
      source:
        plugin:
          name: lovely
```

I had also spent a fair bit of time under the belief that it wasn't properly "registered" via some ConfigMap, however other [issues](https://github.com/crumbhole/argocd-lovely-plugin/issues/362) lead me to understand the `argocd-cm` references in the installation example are vestigial. It'd be excellent to have a means to "test" that the plugin is operating correctly prior to modifying GitOps workloads to make use of it.

Finally, I would consider de-prioritizing the reference to [Argo CD's documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#sidecar-plugin), as this was very confusing, assumes a very different context, and is about how to make a custom plugin.

I'd be happy to PR an update to the README, but it'd be better to open an issue to start the discussion.
