### ISSUE TITLE
LOVELY_ENV_PROPAGATION doesn't update Env variable yaml manifest for kustomization

### ISSUE THREAD

**Issue by Vikaspogu** [crumbhole/argocd-lovely-plugin#690]
Hi, I'm trying to replace environment variables in a YAML file that's part of `kustomization.yaml`. I have attempted to set `LOVELY_ENV_PROPAGATION` and add variables, but it doesn't seem to work. Below are my manifests. Appreciate any help. Thank you!

```yaml
application.yaml
plugin:
        name: argocd-lovely-plugin
        env:
          - name: LOVELY_ENV_PROPAGATION
            value: "true"
          - name: BASE_DOMAIN
            value: "example.com"

kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./staging-cluster-issuer.yaml

staging-cluster-issuer.yaml
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-key
        selector:
          dnsZones:
            - $BASE_DOMAIN
```

 I have tried using $BASE_DOMAIN, ${BASE_DOMAIN}, with ARGOCD_ENV_ and without

**Comment by tico24** [comment]
> Whether to propagate and map ARGOCD_ENV_{VARIABLE} environment variables as {VARIABLE} to the downstream processor (Helm, Kustomize or Helmfile).

I don't see you trying to propagate any ARGOCD_ENV_{VARIABLE} environment variables?

**Comment by Vikaspogu** [comment]
Thank you for the quick response. I am trying to propagate the variable `BASE_DOMAIN` within the `ClusterIssuer` kind under
```
spec
...
     selector:
          dnsZones:
            - $BASE_DOMAIN
 ```
I have tried using variable with different format `$BASE_DOMAIN`, `${BASE_DOMAIN}`, with prefix `ARGOCD_ENV_` as well

**Comment by xannz** [comment]
I also can't seem to get the config `LOVELY_ENV_PROPAGATION` working.

I set the propagation with the sidecar install:

```yaml
      containers:
      - env:
        - name: LOVELY_ENV_PROPAGATION
          value: "true"
        image: ghcr.io/crumbhole/lovely:1.2.2
        imagePullPolicy: IfNotPresent
        name: lovely-plugin
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: lovely-tmp
```

And then in my Argocd App I specify the env var:

```yaml
  source:
    path: kubernetes
    repoURL: https://gitlab.ilabt.imec.be/kvasir/kvasir-server.git
    targetRevision: HEAD
    plugin:
      name: lovely
      env:
        - name: ARGOCD_ENV_HOST
          value: test
```

The helmfile expect the `HOST` env var to be set but when trying to create the app I receive the following error:

```
Unable to create application: application spec for kvasir is invalid: InvalidSpecError: Unable to generate manifests in kubernetes: rpc error: code = Unknown desc = plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `argocd-lovely-plugin` failed exit status 1: 2025/06/04 11:43:30 error running helmfile: exit status 1: in ./helmfile.yaml.gotmpl: failed to read helmfile.yaml.gotmpl: failed to load environment values file "environments/default.yaml.gotmpl": failed to render [environments/default.yaml.gotmpl], because of template: stringTemplate:1:15: executing "stringTemplate" at <requiredEnv "HOST">: error calling requiredEnv: required env var `HOST` is not set
```
