### ISSUE TITLE
ARGOCD_ENV_LOVELY_HELMFILE_PATCH does not work

### ISSUE THREAD

**Issue by hamadodene** [crumbhole/argocd-lovely-plugin#719]
Hi, 
I'm trying to update my helmfile.yaml to set the replicaCount to 0, but the configuration isn't working as expected. Here's what I've tried so far:

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://gitlab/my-repo.git
              revision: HEAD
              directories:
                - path: production/*/*
              pathParamPrefix: app
          - clusters:
              selector:
                matchLabels:
                  env: mylabel
  template:
    metadata:
      namespace: argocd
      name: '{{app.path[2]}}-{{app.path[1]}}'
    spec:
      project: my-project
      source:
        path: '{{app.path}}'
        repoURL: https://gitlab/my-repo.git
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
          env:
            - name: ARGOCD_ENV_LOVELY_HELMFILE_PATCH
              value: |
                [{ "op": "add", "path": "/releases/0/set", "value": { "replicaCount": "0" }}]
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      destination:
        namespace: '{{app.path[1]}}'
        server: https://kubernetes.default.svc

```
My image version:  ghcr.io/crumbhole/lovely-vault-plugin:71b090b877028e663c14f413ed571ca915eb5f99

Maybe I missed something. Here's the current state of my helmfile.yaml:

```yaml
repositories:
  - name: example
    url: {{ requiredEnv "GITLAB_BASE_HELM_CHART_REPO" }}

releases:
- name: myappname
  namespace: mynamespace
  chart:  example/base-chart
  version: 0.1.0
  installed: true
  createNamespace: true
  values:
    - ./values.yaml.gotmpl
```

Thanks in advance for your help.
