### ISSUE TITLE
exit status 1: Error: no cached repository for helm-manager

### ISSUE THREAD

**Issue by gabrielfsousa** [crumbhole/argocd-lovely-plugin#85]
how i fix this error ?

```
rpc error: code = Unknown desc = Manifest generation error (cached): `argocd-lovely-plugin` failed exit status 1: 2022/11/25 12:36:32 exit status 1: Error: no cached repository for helm-manager-daf1ee1308783e5bff6495f156b188a0ededf4f6125cc2a5c95c7274583672ee found. (try 'helm repo update'): open /tmp/.helm/cache/repository/helm-manager-daf1ee1308783e5bff6495f156b188a0ededf4f6125cc2a5c95c7274583672ee-index.yaml: no such file or directory
```

**Comment by gabrielfsousa** [comment]
ArgoCD v2.5.2
Harbor v2.6.0
```
apiVersion: v2
name: weave-scope
version: 1.10.1
dependencies:
- name: weave-scope
  version: 1.0.1
  repository: https://registry.harbor/chartrepo/artifacthub.io
```
```
PS C:\WORK\helm> helm dependency build
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://registry.harbor/chartrepo/artifacthub.io" chart repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "dasmeta" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading weave-scope from repo https://registry.harbor/chartrepo/artifacthub.io
Deleting outdated charts
```

**Comment by Joibel** [comment]
https://registry.harbor/ is a private repo.

Does it require authentication?
Is it reachable from the argocd-repo-server pod?

**Comment by Joibel** [comment]
Does this work if you remove lovely plugin?

**Comment by gabrielfsousa** [comment]
like i said, works if i dont use the plugin.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: weave-scope
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://rancher/k8s/clusters/c-m-bsdxhrnf
      - cluster: prod-me
        url: https://rancher/k8s/clusters/c-m-r2sxk659
      - cluster: prod-nl
        url: https://rancher/k8s/clusters/c-m-j45pbv8s
      - cluster: local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-weave-scope'
    spec:
      project: default
      source:
        repoURL: https://dev.azure.com/ssot/_git/ssot
        targetRevision: HEAD
        path: "weave-scope/{{cluster}}"
        plugin:
          name: argocd-lovely-plugin
      destination:
        server: '{{url}}'
        namespace: 'observability'

      syncPolicy:
        syncOptions:
        - CreateNamespace=true

        automated:
          selfHeal: true
          prune: true
```

**Comment by gabrielfsousa** [comment]
![image](https://user-images.githubusercontent.com/722744/203992354-0c8a798d-b9f0-47af-8bd1-e34f85a7820d.png)

**Comment by Joibel** [comment]
Are you attempting to install a helm version 2 chart here (as in the upstream Chart.yaml has apiVersion: v1 in it)?
If so, this is old and deprecated. I'm not sure why it doesn't work any more.

**Comment by Joibel** [comment]
> like i said, works if i dont use the plugin.

So if you remove the plugin: section it works?

**Comment by gabrielfsousa** [comment]
i habe more information. i run the helm dependency build inside the repo-server pod

```
argocd@argocd-repo-server-6896b56566-bvvmn:/tmp/111$ helm dependency build
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "https://registry.harbor/chartrepo/artifacthub.io" chart repository:
        Get "https://registry.harbor/chartrepo/artifacthub.io/index.yaml": x509: certificate signed by unknown authority
Error: no cached repository for helm-manager-daf1ee1308783e5bff6495f156b188a0ededf4f6125cc2a5c95c7274583672ee found. (try 'helm repo update'): open /helm-working-dir/repository/helm-manager-daf1ee1308783e5bff6495f156b188a0ededf4f6125cc2a5c95c7274583672ee-index.yaml: no such file or directory
argocd@argocd-repo-server-6896b56566-bvvmn:/tmp/111$ helm dependency build --insecure-skip-tls-verify
Error: unknown flag: --insecure-skip-tls-verify
```

**Comment by gabrielfsousa** [comment]
> > like i said, works if i dont use the plugin.
> 
> So if you remove the plugin: section it works?

yes

**Comment by gabrielfsousa** [comment]
upstream Chart.yaml v1 worked in my private k8s

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: weave-scope
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-weave-scope'
    spec:
      project: default
      source:
        repoURL: https://github.com/gabrielfsousa/infra001.git
        targetRevision: HEAD
        path: weave-scope/{{cluster}}
        plugin:
          name: argocd-lovely-plugin
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true

        automated:
          selfHeal: true
          prune: true
```
```
apiVersion: v2
name: weave-scope
version: 0.1.0
dependencies:
- name: weave-scope
  version: 1.0.0
  repository: https://dasmeta.github.io/helm/
```

**Comment by Joibel** [comment]
`Get "https://registry.harbor/chartrepo/artifacthub.io/index.yaml": x509: certificate signed by unknown authority`

That's the problem. I assume you have added this repository to ArgoCD? lovely can't see the certificate you've trusted in ArgoCD  if so, so won't trust it. I don't have a workaround for that.

**Comment by gabrielfsousa** [comment]
yes, its in ArgoCD, in argo i added insecure-skip-tls-verify.

```
apiVersion: v1
kind: Secret
metadata:
  name: repo-harbor
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "false"
  insecure: "true"
  name: "harbor"
  type: helm
  url: "https://registry.harbor/chartrepo/artifacthub.io"
  project: "default"
```
